/*
 * Copyright (c) 2019 Gerson Fernando Budke
 * SPDX-License-Identifier: Apache-2.0
 */

/** @file
 * @brief Atmel SAM4L MCU pin definitions.
 *
 * This file contains pin configuration data required by different MCU
 * modules to correctly configure GPIO controller.
 */

#ifndef _ATMEL_SAM4L_SOC_PINMAP_H_
#define _ATMEL_SAM4L_SOC_PINMAP_H_

#include <soc.h>

/* Universal Synchronous Asynchronous Receiver Transmitter (USART) */

#ifdef CONFIG_USART_SAM_PORT_0_PIN_RXD_PA5
#define PIN_USART0_RXD {PIN_PA05B_USART0_RXD, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#elif CONFIG_USART_SAM_PORT_0_PIN_RXD_PA11
#define PIN_USART0_RXD {PIN_PA11A_USART0_RXD, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#elif CONFIG_USART_SAM_PORT_0_PIN_RXD_PB0
#define PIN_USART0_RXD {PIN_PB00B_USART0_RXD, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#elif CONFIG_USART_SAM_PORT_0_PIN_RXD_PB14
#define PIN_USART0_RXD {PIN_PB14A_USART0_RXD, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#elif CONFIG_USART_SAM_PORT_0_PIN_RXD_PC2
#define PIN_USART0_RXD {PIN_PC02C_USART0_RXD, GPIO, ID_GPIO, SOC_GPIO_FUNC_C}
#endif
#ifdef CONFIG_USART_SAM_PORT_0_PIN_TXD_PA7
#define PIN_USART0_TXD {PIN_PA07B_USART0_TXD, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#elif CONFIG_USART_SAM_PORT_0_PIN_TXD_PA12
#define PIN_USART0_TXD {PIN_PA12A_USART0_TXD, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#elif CONFIG_USART_SAM_PORT_0_PIN_TXD_PB1
#define PIN_USART0_TXD {PIN_PB01B_USART0_TXD, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#elif CONFIG_USART_SAM_PORT_0_PIN_TXD_PB15
#define PIN_USART0_TXD {PIN_PB15A_USART0_TXD, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#elif CONFIG_USART_SAM_PORT_0_PIN_TXD_PC3
#define PIN_USART0_TXD {PIN_PC03C_USART0_TXD, GPIO, ID_GPIO, SOC_GPIO_FUNC_C}
#endif
#ifdef CONFIG_USART_SAM_PORT_0_PIN_CTS_PA9
#define PIN_USART0_CTS {PIN_PA09A_USART0_CTS, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#elif CONFIG_USART_SAM_PORT_0_PIN_CTS_PB11
#define PIN_USART0_CTS {PIN_PB11A_USART0_CTS, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#elif CONFIG_USART_SAM_PORT_0_PIN_CTS_PC2
#define PIN_USART0_CTS {PIN_PC02B_USART0_CTS, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#endif
#ifdef CONFIG_USART_SAM_PORT_0_PIN_RTS_PA6
#define PIN_USART0_RTS {PIN_PA06B_USART0_RTS, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#elif CONFIG_USART_SAM_PORT_0_PIN_RTS_PA8
#define PIN_USART0_RTS {PIN_PA08A_USART0_RTS, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#elif CONFIG_USART_SAM_PORT_0_PIN_RTS_PB12
#define PIN_USART0_RTS {PIN_PB12A_USART0_RTS, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#elif CONFIG_USART_SAM_PORT_0_PIN_RTS_PC1
#define PIN_USART0_RTS {PIN_PC01B_USART0_RTS, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#endif
#ifdef CONFIG_USART_SAM_PORT_0_PIN_CLK_PA4
#define PIN_USART0_SCK {PIN_PA04B_USART0_CLK, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#elif CONFIG_USART_SAM_PORT_0_PIN_CLK_PA10
#define PIN_USART0_SCK {PIN_PA10A_USART0_CLK, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#elif CONFIG_USART_SAM_PORT_0_PIN_CLK_PB13
#define PIN_USART0_SCK {PIN_PB13A_USART0_CLK, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#elif CONFIG_USART_SAM_PORT_0_PIN_CLK_PC0
#define PIN_USART0_SCK {PIN_PC00B_USART0_CLK, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#endif

#define PINS_USART0 {PIN_USART0_RXD, PIN_USART0_TXD, PIN_USART0_CTS, \
		     PIN_USART0_RTS, PIN_USART0_SCK}

#ifdef CONFIG_USART_SAM_PORT_1_PIN_RXD_PA15
#define PIN_USART1_RXD {PIN_PA15A_USART1_RXD, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#elif CONFIG_USART_SAM_PORT_1_PIN_RXD_PB4
#define PIN_USART1_RXD {PIN_PB04B_USART1_RXD, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#elif CONFIG_USART_SAM_PORT_1_PIN_RXD_PC26
#define PIN_USART1_RXD {PIN_PC26A_USART1_RXD, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#endif
#ifdef CONFIG_USART_SAM_PORT_1_PIN_TXD_PA16
#define PIN_USART1_TXD {PIN_PA16A_USART1_TXD, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#elif CONFIG_USART_SAM_PORT_1_PIN_TXD_PB5
#define PIN_USART1_TXD {PIN_PB05B_USART1_TXD, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#elif CONFIG_USART_SAM_PORT_1_PIN_TXD_PC27
#define PIN_USART1_TXD {PIN_PC27A_USART1_TXD, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#endif
#define PIN_USART1_CTS {PIN_PA21B_USART1_CTS, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#ifdef CONFIG_USART_SAM_PORT_1_PIN_RTS_PA13
#define PIN_USART1_RTS {PIN_PA13A_USART1_RTS, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#elif CONFIG_USART_SAM_PORT_1_PIN_RTS_PB2
#define PIN_USART1_RTS {PIN_PB02B_USART1_RTS, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#elif CONFIG_USART_SAM_PORT_1_PIN_RTS_PC24
#define PIN_USART1_RTS {PIN_PC24A_USART1_RTS, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#endif
#ifdef CONFIG_USART_SAM_PORT_1_PIN_CLK_PA14
#define PIN_USART1_SCK {PIN_PA14A_USART1_SCK, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#elif CONFIG_USART_SAM_PORT_1_PIN_CLK_PB3
#define PIN_USART1_SCK {PIN_PB03B_USART1_SCK, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#elif CONFIG_USART_SAM_PORT_1_PIN_CLK_PC25
#define PIN_USART1_SCK {PIN_PC25A_USART1_SCK, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#endif

#define PINS_USART1 {PIN_USART1_RXD, PIN_USART1_TXD, PIN_USART1_CTS, \
		     PIN_USART1_RTS, PIN_USART1_SCK}

#ifdef CONFIG_USART_SAM_PORT_2_PIN_RXD_PA19
#define PIN_USART2_RXD {PIN_PA19A_USART2_RXD, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#elif CONFIG_USART_SAM_PORT_2_PIN_RXD_PA25
#define PIN_USART2_RXD {PIN_PA25B_USART2_RXD, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#elif CONFIG_USART_SAM_PORT_2_PIN_RXD_PC11
#define PIN_USART2_RXD {PIN_PC11B_USART2_RXD, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#endif
#ifdef CONFIG_USART_SAM_PORT_2_PIN_TXD_PA20
#define PIN_USART2_TXD {PIN_PA20A_USART2_TXD, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#elif CONFIG_USART_SAM_PORT_2_PIN_TXD_PA26
#define PIN_USART2_TXD {PIN_PA26B_USART2_TXD, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#elif CONFIG_USART_SAM_PORT_3_PIN_TXD_PC12
#define PIN_USART2_TXD {PIN_PC12B_USART2_TXD, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#endif
#ifdef CONFIG_USART_SAM_PORT_2_PIN_CTS_PA22
#define PIN_USART2_CTS {PIN_PA22B_USART2_CTS, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#elif CONFIG_USART_SAM_PORT_2_PIN_CTS_PC8
#define PIN_USART2_CTS {PIN_PC08E_USART2_CTS, GPIO, ID_GPIO, SOC_GPIO_FUNC_E}
#endif
#ifdef CONFIG_USART_SAM_PORT_2_PIN_RTS_PA17
#define PIN_USART2_RTS {PIN_PA17A_USART2_RTS, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#elif CONFIG_USART_SAM_PORT_2_PIN_RTS_PC7
#define PIN_USART2_RTS {PIN_PC07B_USART2_RTS, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#endif
#ifdef CONFIG_USART_SAM_PORT_2_PIN_CLK_PA18
#define PIN_USART2_SCK {PIN_PA18A_USART2_SCK, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#elif CONFIG_USART_SAM_PORT_2_PIN_CLK_PC8
#define PIN_USART2_SCK {PIN_PC08B_USART2_SCK, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#endif

#define PINS_USART2 {PIN_USART2_RXD, PIN_USART2_TXD, PIN_USART2_CTS, \
		     PIN_USART2_RTS, PIN_USART2_SCK}

#ifdef CONFIG_USART_SAM_PORT_3_PIN_RXD_PA30
#define PIN_USART3_RXD {PIN_PA30A_USART3_RXD, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#elif CONFIG_USART_SAM_PORT_3_PIN_RXD_PB9
#define PIN_USART3_RXD {PIN_PB09A_USART3_RXD, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#elif CONFIG_USART_SAM_PORT_3_PIN_RXD_PC9
#define PIN_USART3_RXD {PIN_PC09A_USART3_RXD, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#elif CONFIG_USART_SAM_PORT_3_PIN_RXD_PC28
#define PIN_USART3_RXD {PIN_PC28A_USART3_RXD, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#endif
#ifdef CONFIG_USART_SAM_PORT_3_PIN_TXD_PA31
#define PIN_USART3_TXD {PIN_PA30E_USART3_TXD, GPIO, ID_GPIO, SOC_GPIO_FUNC_E}
#elif CONFIG_USART_SAM_PORT_3_PIN_TXD_PB10
#define PIN_USART3_TXD {PIN_PB10A_USART3_TXD, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#elif CONFIG_USART_SAM_PORT_3_PIN_TXD_PC10
#define PIN_USART3_TXD {PIN_PC10B_USART3_TXD, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#elif CONFIG_USART_SAM_PORT_3_PIN_TXD_PC29
#define PIN_USART3_TXD {PIN_PC29A_USART3_TXD, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#endif
#ifdef CONFIG_USART_SAM_PORT_3_PIN_CTS_PA28
#define PIN_USART3_CTS {PIN_PA28E_USART3_CTS, GPIO, ID_GPIO, SOC_GPIO_FUNC_E}
#elif CONFIG_USART_SAM_PORT_3_PIN_CTS_PB7
#define PIN_USART3_CTS {PIN_PB07A_USART3_CTS, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#endif
#ifdef CONFIG_USART_SAM_PORT_3_PIN_RTS_PA27
#define PIN_USART3_RTS {PIN_PA27E_USART3_RTS, GPIO, ID_GPIO, SOC_GPIO_FUNC_E}
#elif CONFIG_USART_SAM_PORT_3_PIN_RTS_PB6
#define PIN_USART3_RTS {PIN_PB06A_USART3_RTS, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#elif CONFIG_USART_SAM_PORT_3_PIN_RTS_PC13
#define PIN_USART3_RTS {PIN_PC13B_USART3_RTS, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#elif CONFIG_USART_SAM_PORT_3_PIN_RTS_PC30
#define PIN_USART3_RTS {PIN_PC30A_USART3_RTS, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#endif
#ifdef CONFIG_USART_SAM_PORT_3_PIN_CLK_PA29
#define PIN_USART3_SCK {PIN_PA29E_USART3_SCK, GPIO, ID_GPIO, SOC_GPIO_FUNC_E}
#elif CONFIG_USART_SAM_PORT_3_PIN_CLK_PB8
#define PIN_USART3_SCK {PIN_PB08A_USART3_SCK, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#elif CONFIG_USART_SAM_PORT_3_PIN_CLK_PC14
#define PIN_USART3_SCK {PIN_PC14B_USART3_SCK, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#elif CONFIG_USART_SAM_PORT_3_PIN_CLK_PC31
#define PIN_USART3_SCK {PIN_PC31A_USART3_SCK, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#endif

#define PINS_USART3 {PIN_USART3_RXD, PIN_USART3_TXD, PIN_USART3_CTS, \
		     PIN_USART3_RTS, PIN_USART3_SCK}

/* Two-wire Interface (TWI) */

#define PIN_TWI0_TWCK {PIN_PA24A_TWCK0, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#define PIN_TWI0_TWD  {PIN_PA23A_TWD0,  GPIO, ID_GPIO, SOC_GPIO_FUNC_B}

#define PINS_TWI0 {PIN_TWI0_TWCK, PIN_TWI0_TWD}

#define PIN_TWI1_TWCK {PIN_PB01A_TWIMS1_TWCK, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#define PIN_TWI1_TWD  {PIN_PB00A_TWIMS1_TWD,  GPIO, ID_GPIO, SOC_GPIO_FUNC_A}

#define PINS_TWI1 {PIN_TWI1_TWCK, PIN_TWI1_TWD}

#define PIN_TWI2_TWCK {PIN_PA22A_TWCK2, GPIO, ID_GPIO, SOC_GPIO_FUNC_E}
#define PIN_TWI2_TWD  {PIN_PA21A_TWD2,  GPIO, ID_GPIO, SOC_GPIO_FUNC_E}

#define PINS_TWI2 {PIN_TWI2_TWCK, PIN_TWI2_TWD}

#define PIN_TWI3_TWCK {PIN_PB15C_TWCK3, GPIO, ID_GPIO, SOC_GPIO_FUNC_C}
#define PIN_TWI3_TWD  {PIN_PB14C_TWD3,  GPIO, ID_GPIO, SOC_GPIO_FUNC_C}

#define PINS_TWI3 {PIN_TWI3_TWCK, PIN_TWI3_TWD}

/* Serial Peripheral Interface (SPI) */

#ifdef CONFIG_SPI_SAM_PORT_0_PIN_CS0_PA2
#define PIN_SPI0_CS0 {PIN_PA02B_SPI_NPCS0, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#endif
#ifdef CONFIG_SPI_SAM_PORT_0_PIN_CS0_PA24
#define PIN_SPI0_CS0 {PIN_PA24A_SPI_NPCS0, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#endif
#ifdef CONFIG_SPI_SAM_PORT_0_PIN_CS0_PA30
#define PIN_SPI0_CS0 {PIN_PA30A_SPI_NPCS0, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#endif
#ifdef CONFIG_SPI_SAM_PORT_0_PIN_CS0_PC3
#define PIN_SPI0_CS0 {PIN_PC03A_SPI_NPCS0, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#endif
#ifdef CONFIG_SPI_SAM_PORT_0_PIN_CS0_PC31
#define PIN_SPI0_CS0 {PIN_PC31B_SPI_NPCS0, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#endif

#ifdef CONFIG_SPI_SAM_PORT_0_PIN_CS1_PA13
#define PIN_SPI0_CS1 {PIN_PA13C_SPI_NPCS1, GPIO, ID_GPIO, SOC_GPIO_FUNC_C}
#endif
#ifdef CONFIG_SPI_SAM_PORT_0_PIN_CS1_PA31
#define PIN_SPI0_CS1 {PIN_PA31A_SPI_NPCS1, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#endif
#ifdef CONFIG_SPI_SAM_PORT_0_PIN_CS1_PB13
#define PIN_SPI0_CS1 {PIN_PB13B_SPI_NPCS1, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#endif
#ifdef CONFIG_SPI_SAM_PORT_0_PIN_CS1_PC2
#define PIN_SPI0_CS1 {PIN_PC02A_SPI_NPCS1, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#endif

#ifdef CONFIG_SPI_SAM_PORT_0_PIN_CS2_PA14
#define PIN_SPI0_CS2 {PIN_PA14C_SPI_NPCS2, GPIO, ID_GPIO, SOC_GPIO_FUNC_C}
#endif
#ifdef CONFIG_SPI_SAM_PORT_0_PIN_CS2_PB11
#define PIN_SPI0_CS2 {PIN_PB11B_SPI_NPCS2, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#endif
#ifdef CONFIG_SPI_SAM_PORT_0_PIN_CS2_PC0
#define PIN_SPI0_CS2 {PIN_PC00A_SPI_NPCS2, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#endif

#ifdef CONFIG_SPI_SAM_PORT_0_PIN_CS3_PA15
#define PIN_SPI0_CS3 {PIN_PA15C_SPI_NPCS3, GPIO, ID_GPIO, SOC_GPIO_FUNC_C}
#endif
#ifdef CONFIG_SPI_SAM_PORT_0_PIN_CS3_PB12
#define PIN_SPI0_CS3 {PIN_PB12B_SPI_NPCS3, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#endif
#ifdef CONFIG_SPI_SAM_PORT_0_PIN_CS3_PC1
#define PIN_SPI0_CS3 {PIN_PC01A_SPI_NPCS3, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#endif

#ifdef CONFIG_SPI_SAM_PORT_0_PIN_MISO_PA3
#define PIN_SPI0_MISO {PIN_PA03B_SPI_MISO, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#endif
#ifdef CONFIG_SPI_SAM_PORT_0_PIN_MISO_PA21
#define PIN_SPI0_MISO {PIN_PA21A_SPI_MISO, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#endif
#ifdef CONFIG_SPI_SAM_PORT_0_PIN_MISO_PA27
#define PIN_SPI0_MISO {PIN_PA27A_SPI_MISO, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#endif
#ifdef CONFIG_SPI_SAM_PORT_0_PIN_MISO_PB14
#define PIN_SPI0_MISO {PIN_PB14B_SPI_MISO, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#endif
#ifdef CONFIG_SPI_SAM_PORT_0_PIN_MISO_PC4
#define PIN_SPI0_MISO {PIN_PC04A_SPI_MISO, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#endif
#ifdef CONFIG_SPI_SAM_PORT_0_PIN_MISO_PC28
#define PIN_SPI0_MISO {PIN_PC28B_SPI_MISO, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#endif

#ifdef CONFIG_SPI_SAM_PORT_0_PIN_MOSI_PA22
#define PIN_SPI0_MOSI {PIN_PA22A_SPI_MOSI, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#endif
#ifdef CONFIG_SPI_SAM_PORT_0_PIN_MOSI_PA28
#define PIN_SPI0_MOSI {PIN_PA28A_SPI_MOSI, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#endif
#ifdef CONFIG_SPI_SAM_PORT_0_PIN_MOSI_PB15
#define PIN_SPI0_MOSI {PIN_PB15B_SPI_MOSI, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#endif
#ifdef CONFIG_SPI_SAM_PORT_0_PIN_MOSI_PC5
#define PIN_SPI0_MOSI {PIN_PC05A_SPI_MOSI, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#endif
#ifdef CONFIG_SPI_SAM_PORT_0_PIN_MOSI_PC29
#define PIN_SPI0_MOSI {PIN_PC29B_SPI_MOSI, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#endif

#ifdef CONFIG_SPI_SAM_PORT_0_PIN_SCK_PA23
#define PIN_SPI0_SCK {PIN_PA23A_SPI_SCK, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#endif
#ifdef CONFIG_SPI_SAM_PORT_0_PIN_SCK_PA29
#define PIN_SPI0_SCK {PIN_PA29A_SPI_SCK, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#endif
#ifdef CONFIG_SPI_SAM_PORT_0_PIN_SCK_PC6
#define PIN_SPI0_SCK {PIN_PC06A_SPI_SCK, GPIO, ID_GPIO, SOC_GPIO_FUNC_A}
#endif
#ifdef CONFIG_SPI_SAM_PORT_0_PIN_SCK_PC30
#define PIN_SPI0_SCK {PIN_PC30B_SPI_SCK, GPIO, ID_GPIO, SOC_GPIO_FUNC_B}
#endif

#define PINS_SPI0 {PIN_SPI0_MISO, PIN_SPI0_MOSI, PIN_SPI0_SCK}

#endif /* _ATMEL_SAM4L_SOC_PINMAP_H_ */
